# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c

before_install:
  - gem install xcpretty

script:
- xcodebuild test -scheme gausskrueger-macOS | xcpretty
- swift test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
